Homework 1 files
sergeysablin99/AdvCpp pull request #4
Opened 2020-03-19 19:27 UTC by sergeysablin99

2020-03-20 11:34 UTC, smirnov-vs requested changes
Нужно в корне переписать работу с исключительными ситуациями, библиотека совсем не позволяет отслеживать ошибки
Остальное по мелочи в построчных комментариях

2020-03-20 11:34 UTC, smirnov-vs commented on include/process.hpp
> +    int pipefd_cp[2];
в состоянии класса достаточно хранить только 2 дескриптора

2020-03-20 11:34 UTC, smirnov-vs commented on include/process.hpp
> +    int cpid;
обычно `pid_t`

2020-03-20 11:34 UTC, smirnov-vs commented on source/main.cpp
> +#include "../include/process.hpp"
Надо оформить include красиво

2020-03-20 11:34 UTC, smirnov-vs commented on source/main.cpp
> +    Process process("./echo");
процесс захардкожен, мне придется догадываться как запустить программу вплоть до заглядывания в исходники

2020-03-20 11:34 UTC, smirnov-vs commented on source/main.cpp
> +    return 0;
нет никакой обработки ошибок

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        exit(EXIT_FAILURE);
на лекции говорили, что exit не подходит, исправляем

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        perror("Pipe error");
библиотеки не общаются с консолью

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +            perror("Close error");
как ловить эту ошибку?

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        if (execl(path.data(), NULL) == -1) {
тут забыл еще первый аргумент
обычно там хранится путь к файлу программы

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        if (execl(path.data(), NULL) == -1) {
в C++ используется nullptr

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        c = read(a, sizeof(a));
остался дебаг код

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +    int bytes_to_write = len;
разные типы данных

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +    while(bytes_to_write) {
это не bool, надо сравнивать

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        bytes_to_write = bytes_to_write - write(data, bytes_to_write);
будет лучше написать через `-=`

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +    int reply = ::read(pipefd_cp[0], data, len);
read возвращает не `int`

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +    exit((EXIT_SUCCESS));
почему программа завершается?

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +        reply = ::close(pipefd_cp[0]);
`close` возвращает не `size_t`

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +    reply = ::close(pipefd_pc[1]);
почему закрывается сразу 2 дескриптора?

2020-03-20 11:34 UTC, smirnov-vs commented on source/process.cpp
> +    return ::read(pipefd_cp[0], &a, 1) != -1 and ::write(pipefd_pc[1], b, sizeof(b)) != -1;
это в корне неверно, проверка не должна нести каких-либо дополнительных затрат
нужно сделать по-другому

2020-03-20 18:09 UTC, sergeysablin99 commented on source/process.cpp
> +        perror("Pipe error");
Корректно выводит в консоль соощение, или Вы имели в виду другое?

![perror](https://user-images.githubusercontent.com/55097962/77193274-09a8b200-6aef-11ea-90a0-b5afa0e453b8.png)

2020-03-23 20:38 UTC, smirnov-vs commented on source/process.cpp
> +        perror("Pipe error");
да, но это бесполезно, я не смогу поймать эту ошибку у себя

2020-03-23 20:39 UTC, smirnov-vs commented on source/process.cpp
> +        perror("Pipe error");
Александр говорил уже про это в 2 лекции, думаю поймешь о чем я)

2020-03-23 20:46 UTC, smirnov-vs requested changes
Нужно кардинально задуматься и переработать систему ошибок, 2 лекция тебе сильно поможет
И фиксим все оставшиеся замечания

2020-03-23 20:46 UTC, smirnov-vs commented on source/process.cpp
> +    while(bytes_to_read)
я писал про такую ошибку в другой строке, исправлять и искать нужно везде

2020-03-23 20:46 UTC, smirnov-vs commented on source/process.cpp
> +    return fstat(fd_read, &sb) != -1;
когда read дошел до eof, достаточно пометить, что все, поток кончился, метод работает без сисколлов

2020-03-23 20:46 UTC, smirnov-vs commented on source/process.cpp
> +        throw "Cannot open fd to read";
как исключения бросают классы, тоже уже есть инфа в 2 лекции

2020-03-23 20:46 UTC, smirnov-vs commented on source/main.cpp
> +        char buffer[24] = "Error: no path provided";
`const char*`
но на самом деле переменную объявлять не надо

2020-03-23 20:46 UTC, smirnov-vs commented on source/main.cpp
> +            fwrite(error, 1, sizeof(error), stdout);
почему пишем на си? переезжаем на язык нашего курса

2020-03-23 20:46 UTC, smirnov-vs commented on source/echo.cpp
> +        fwrite(buffer, 1, bytes, stdout);
мой пример написан на си только потому, что это универсально работает для любых данных, пропущенных через процесс

2020-03-24 23:57 UTC, smirnov-vs requested changes

2020-03-24 23:57 UTC, smirnov-vs commented on source/process.cpp
> +    eof = reply == len;
почему такая проверка?

2020-03-24 23:57 UTC, smirnov-vs commented on source/process.cpp
> +        throw Exception("Fork error");
пайпы утекли

2020-03-25 21:41 UTC, smirnov-vs commented on source/process.cpp
> +    eof = reply == 0;
я бы для читаемости в скобки завернул

2020-03-25 21:41 UTC, smirnov-vs commented on source/process.cpp
> +        close();
а чего заодно и убиваем? он же -1

2020-03-28 12:34 UTC, smirnov-vs approved these changes
задачку зачел, так как уже неделя прошла

2020-03-28 12:34 UTC, smirnov-vs commented on source/process.cpp
> +        throw Exception("Fork error");
есть места где утекают ресурсы

2020-03-28 12:35 UTC, merged