Hw2
sergeysablin99/AdvCpp pull request #5
Opened 2020-03-26 16:13 UTC by sergeysablin99

2020-03-26 19:29 UTC, a-badin requested changes

2020-03-26 19:29 UTC, a-badin commented on CMakeLists.txt
> +add_library(base_logger STATIC source/base_logger.cpp)
Зачем столько библиотек) Давайте постараемся уместить в одну.

2020-03-26 19:29 UTC, a-badin commented on include/base_logger.h
> +
отдельный namespace на библиотеку

2020-03-26 19:29 UTC, a-badin commented on include/base_logger.h
> +    enum Level {
Лучше вынести enum за пределы класса BaseLogger. И лучше сделать его enum class

2020-03-26 19:29 UTC, a-badin commented on include/base_logger.h
> +    Level level() noexcept;
раз уж мы ставим noexept то и const было бы здорово

2020-03-26 19:29 UTC, a-badin commented on include/base_logger.h
> +    const char * what() noexcept { return msg.c_str(); };
override

2020-03-26 19:29 UTC, a-badin commented on include/file_logger.h
> +    explicit FileLogger(const std::string& path, Level level);
Или level сделать default или explicit убрать

2020-03-26 19:29 UTC, a-badin commented on source/file_logger.cpp
> +        output.clear();
Ему жить осталось 1 строчку - зачем его чистить

2020-03-26 19:29 UTC, a-badin commented on source/file_logger.cpp
> +FileLogger::FileLogger(std::ofstream&& other, Level level) : output(std::move(other)) {}
А level проигнорировали

2020-03-26 19:29 UTC, a-badin commented on source/file_logger.cpp
> +    if (level >= this->level()) {
не надо писать this->

2020-03-26 19:29 UTC, a-badin commented on source/file_logger.cpp
> +        switch (level) {
У вас вот эта логика повторяется в 3 местах. Я на следующей неделе вам дам еще 3 уровня: Trace, Verbose и Critical. Вы будете в 9 местах код править? Сделайте метод std::string get_level_prefix(Level level) в BaseLogger, например.

2020-03-26 19:29 UTC, a-badin commented on include/stderr_logger.h
> +    explicit StderrLogger( Level level) noexcept;
отступ поехал

2020-03-26 19:29 UTC, a-badin commented on include/logger.h
> +#include <file_logger.h>
Свои заголовчные файлы лучше чтобы компилятор в первую очередь искал в  include_directories, поэтому их добавляют через "file_logger.h", а системные сначала лучше искать в системных путях, поэтому их добавляют через <>

2020-03-26 19:29 UTC, a-badin commented on include/logger.h
> +    explicit Logger();
explicit не нужен если число параметров не 1

2020-03-26 19:29 UTC, a-badin commented on include/logger.h
> +    void set_global_logger(BaseLogger* logger);
Вот тут есть неоднозначность, как **явно** "сказать" тому, кто захочет вызвать set_global_logger, что владение переданным logger'ом перейдет в Logger?

2020-03-26 19:29 UTC, a-badin commented on include/logger.h
> +StdoutLogger* create_file_logger(BaseLogger::Level level);
Имя метода неправильное

2020-03-26 19:29 UTC, a-badin commented on source/logger.cpp
> +    Logger& logger = Logger::get_instance();
Вам просто нужно создать FileLogger и вернуть его, это то что говорит нам метод create_file_logger

2020-03-26 19:29 UTC, a-badin commented on source/logger.cpp
> +StdoutLogger* create_file_logger(BaseLogger::Level level) {
Верните unique_ptr<BaseLogger>

2020-04-01 15:48 UTC, a-badin commented on source/logger.cpp
> +void debug(const std::string& msg) {
Вот так не правильно определять методы, если попробуйте вызвать любой из них - у вас будет undefined reference. Все определения кладем в namespace logger

2020-04-01 15:48 UTC, a-badin commented on source/logger.cpp
> +    Logger& logger = Logger::get_instance();
Еще раз, не нужно ничего инициализировать, сделайте ровно то что говорит название метода - create_file_logger, вы должны создать логгер и вернуть его

2020-04-01 16:39 UTC, a-badin requested changes

2020-04-01 16:39 UTC, a-badin commented on include/stderr_logger.h
> +        ~StderrLogger() noexcept = default;
Можно не писать, компилятор сделает сам

2020-04-01 16:39 UTC, a-badin commented on include/logger.h
> +#include "file_logger.h"
Вам для объявления достаточно BaseLogger

2020-04-01 16:39 UTC, a-badin commented on include/logger.h
> +#include "memory"
Всегда добавляем системные заголовки в <>, а свои в ""
https://gcc.gnu.org/onlinedocs/cpp/Search-Path.html

2020-04-01 16:39 UTC, a-badin commented on include/logger.h
> +        std::unique_ptr<BaseLogger> get_global_logger();
Получается любое обращение к синглтону - и синглтон больше не может ничего писать.
А как мне вызвать
logger::info("Info msg");
logger::debug("Debug msg");
Первый же вызов сломает синглтон Logger

2020-04-01 16:39 UTC, a-badin commented on source/logger.cpp
> +void Logger::set_global_logger(BaseLogger&& logger) {
В принципе вариант, но есть пара моментов
Момент первый, rvalue reference BaseLogger&& здесь работает точно также как в move конструкторах, поэтому ресурсы у logger нужно заменить на не валидные. У вас сначала ресурсы закроет global_logger_, потому что вы ему передали указатель, а второй раз ресурсы освободит сам logger вне этого метода.
Момент второй, некоторые ресурсы вы заменить не сможете, так как некоторые поля у logger могут быть private. Но вы могли бы инициализировать unique_ptr через move на logger, например, так global_logger_ = std::make_unique<BaseLogger>(std::move(logger));
Момент третий, вышесказанный вариант не сработает, потому что BaseLogger абстрактынй, но даже если бы он не был. Вы не знаете конкретную реализацию logger, это может быть FileLogger или любой другой. Поэтому вы не знаете даже какого размера должен быть указатель в global_logger_, чтобы уместить все поля в logger.

Итог такой, что единственный вариант для вас, это принимать на вход unique_ptr

2020-04-01 16:39 UTC, a-badin commented on source/logger.cpp
> +    Logger::get_instance().get_global_logger()->info(msg);
Вы бы хоть попробовали вызвать этот метод - сразу было бы видно ошибку

2020-04-04 11:27 UTC, a-badin requested changes

2020-04-04 11:27 UTC, a-badin commented on source/logger.cpp
> +void logger::info(const std::string& msg) {
не проще один раз открыть namespace вверху и не писать logger:: в определении каждого метода?

2020-04-04 11:27 UTC, a-badin commented on source/logger.cpp
> +    global_logger_.reset(logger.get());
global_logger_ = std::move(logger) чуть-чуть проще

2020-04-04 11:27 UTC, a-badin commented on source/logger.cpp
> +    Logger::get_instance().get_global_logger()->warn(msg);
А если get_global_logger пустой?

2020-04-04 11:27 UTC, a-badin commented on source/main.cpp
> +    return 0;
Давайте делать примеры по-интереснее, вы сможете сразу ловить свои же ошибки

2020-04-04 11:27 UTC, a-badin commented on include/base_logger.h
> +        std::string msg;
дэш на приватных членах данных

2020-04-04 11:33 UTC, sergeysablin99 commented on source/main.cpp
> +    return 0;
Я удалил пример, чтобы не было конфликтов с мастер веткой 😅

2020-04-07 13:40 UTC, closed without merging