TCP library
sergeysablin99/AdvCpp pull request #6
Opened 2020-04-01 12:09 UTC by sergeysablin99

2020-04-05 14:09 UTC, smirnov-vs requested changes

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/CMakeLists.txt
> +add_executable(tcp_main source/main.cpp)
а где main.cpp?

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/source/connection.cpp
> +    ssize_t reply = ::write(fd_, data, size);
?

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/source/connection.cpp
> +    ssize_t reply = ::write(fd_, data, size);
код не тестировался, приложи main с тестом

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/source/server.cpp
> +void Server::set_max_connect(int count) {
для количеств обычно size_t

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/source/server.cpp
> +}
тут есть утечки

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/source/server.cpp
> +    close();
а почему так?

2020-04-05 14:09 UTC, smirnov-vs commented on tcp/source/server.cpp
> +Server::Server(in_addr ip, in_port_t port) : opened(true), connections(1), addr_(ip), port_(port) {
такой интерфейс не очень удобный для ввода ip

2020-04-06 12:02 UTC, sergeysablin99 commented on tcp/source/server.cpp
> +    close();
Изначально я хотел пометить, что нужно заново открыть сервер, чтобы получить новый дескриптор сокета, т.к. старый завязан на входящее соединение и переходит в Connection. Но закрываю я старый, это ошибка

2020-04-07 11:16 UTC, closed without merging